version: "3.4"

services:
  node:
    build: ./node-app
    ports:
      - 80:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: